### PR TITLE
Initialize empty RichTextAreaComponent if ActionText not installed, to fix Zeitwerk error

### LINKED ISSUE #119: Create empty class for ViewComponent::Form::RichTextAreaComponent
On production latest release raise this error:

```
~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded': expected file ~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/view_component-form-0.2.2/app/components/view_component/form/rich_text_area_component.rb to define constant ViewComponent::Form::RichTextAreaComponent, but didn't (Zeitwerk::NameError)
```

```
$ bin/rails zeitwerk:check
Hold on, I am eager loading the application.
expected file ~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/view_component-form-0.2.2/app/components/view_component/form/rich_text_area_component.rb to define constant ViewComponent::Form::RichTextAreaComponent
```

We should do the same that we did for `WeekdaySelectComponent` (https://github.com/pantographe/view_component-form/pull/115)

### PR DESCRIPTION
**Pull request by nicolas-brousse**
Closes #119

### CODE REVIEW

File: app/components/view_component/form/rich_text_area_component.rb [hunk 1]
```diff
@@ -1,10 +1,14 @@
...
-    module Form
-      class RichTextAreaComponent < FieldComponent
+module ViewComponent
+  module Form
+    class RichTextAreaComponent < FieldComponent
+      if defined?(ActionView::Helpers::Tags::ActionText)
         self.tag_klass = ActionView::Helpers::Tags::ActionText
+      else
+        def call
+          raise NotImplementedError, "#{self.class} require action_text to be loaded"
```
Comment (Spone) [inline app/components/view_component/form/rich_text_area_component.rb:10]:
```suggestion
          raise NotImplementedError, "#{self.class} requires action_text to be loaded"
```

**Review by Spone — APPROVED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -5,7 +5,8 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
 ## [Unreleased]
-Nothing yet
+### Fixed
+- Initialize empty RichTextAreaComponent if ActionText not installed, to fix Zeitwerk error (#120)
```
Comment (Spone) [inline CHANGELOG.md:9]:
```suggestion
- Declare empty RichTextAreaComponent if ActionText is not installed, to fix Zeitwerk error (#120)
```

File: app/components/view_component/form/rich_text_area_component.rb [hunk 3]
```diff
@@ -1,10 +1,14 @@
...
-      class RichTextAreaComponent < FieldComponent
+module ViewComponent
+  module Form
+    class RichTextAreaComponent < FieldComponent
+      if defined?(ActionView::Helpers::Tags::ActionText)
         self.tag_klass = ActionView::Helpers::Tags::ActionText
+      else
+        def call
+          raise NotImplementedError, "#{self.class} requires action_text to be loaded"
+        end
```
Comment (nicolas-brousse) [inline app/components/view_component/form/rich_text_area_component.rb:11]: @Spone I'm finally not sure about having this since the helper in builder will not be defined if `action_text` not loaded.

Maybe we should just keep the if part, and remove the else one.

Comment (Spone) [reply app/components/view_component/form/rich_text_area_component.rb:11]: Sounds good!

Comment (Spone) [reply app/components/view_component/form/rich_text_area_component.rb:11]: Sounds good!

Comment (nicolas-brousse) [reply app/components/view_component/form/rich_text_area_component.rb:11]: Ok, I'll do the change then

**Review by Spone — APPROVED** [review]
